default:
  PAGINATOR:
    PageSize: 50
  LOG_DIR: log
  OUTPUT_DIR: download
  INFO_LOG_FILENAME: app.log
  DEBUG_LOG_FILENAME: debug.log
  WARNING_LOG_FILENAME: warning.log
  ERROR_LOG_FILENAME: error.log
  ENCONING: windows-1251
  

